import json,re,html
from pathlib import Path
from datetime import datetime,timezone
from pypdf import PdfReader
P=Path(__file__).parent;R=P/'raw';now=datetime.now(timezone.utc).isoformat()
p=P.parent/'parent_overrides.jsonl';rows=[json.loads(l) for l in p.read_text().splitlines()];rows=[r for r in rows if r['id'] not in ['COSZO-REF-004','COSZO-REF-023','COSZO-REF-033','COSZO-REF-039']]
def record(n,title,url,pdf):
 return dict(id=f'COSZO-REF-{n:03d}',resolved_title=title,resolved_doi=None,paper_url=url,abstract=None,abstract_status='no_abstract_expected',abstract_source_url=None,retrieved_at=now,metadata_source_url=url,license=None,full_text_url=pdf,full_text_status='downloaded_for_inspection',notes=['Report uses a preface/executive summary rather than a conventional abstract. Title, authors and year verified from report front matter.'],attempts=[{'url':url,'result':'Author/institutional landing page identifies exact report.'},{'url':pdf,'result':'Retrieved report and inspected front matter and contents.'}],retrieval_batch='parent',raw_source_file=f'coszo_retrieval_provenance/parent/raw/{n:03d}_report.pdf')
r=record(4,'Future Geophysical Facilities Required to Address Grand Challenges in the Earth Sciences','https://www.iris.edu/hq/workshops/2015/05/future_seismic_and_geodetic_facility_needs_in_the_geosciences?eid=15&view_whitepaper=1','https://www.iris.edu/hq/files/workshops/2015/05/fusg/reports/futures_report.pdf');rows.append(r)
r=record(23,'A Foundation for Innovation: Grand Challenges in Geodesy','https://serc.carleton.edu/NAGTWorkshops/structure/SGT2012/geodesy_frontiers.html','https://cdn.serc.carleton.edu/files/NAGTWorkshops/structure/SGT2012/grand_challenges_geodesy.pdf');r['license']='https://creativecommons.org/licenses/by-nc-sa/3.0/';r['license_scope']='SERC file-specific reuse statement';t=PdfReader(R/'023_report.pdf').pages[1].extract_text();t=t.split('Preface',1)[1];t=re.sub(r'\s+i\s*$','',t);r['source_description']=re.sub(r'\s+',' ',t).strip();r['source_description_type']='report_preface';r['source_description_url']=r['full_text_url'];rows.append(r)
if (R/'033_report.pdf').exists():
 reader=PdfReader(R/'033_report.pdf');text='\n'.join(p.extract_text() for p in reader.pages[:6]);(R/'033_excerpt.txt').write_text(text)
 r=record(33,'Measuring the Restless Earth: Grand Challenges in Geodesy','https://www.mari-odu.org/people/hpplag/index.php?fname=Reports','https://www.mari-odu.org/people/hpplag/pubs/measuring-the-restless-earth.pdf');r['notes'].append('Source citation specifies an executive summary for the NSF/NAS CORES assessment; located full 2019 workshop report, not independently verified exact executive-summary edition.');r['attempts'] += [{'url':'https://www.unavco.org/community/publications_and_reports/community-vision/geodesy_science_plan/measuring-the-restless-earth.pdf','result':'404; used report coauthor mirror.'}];rows.append(r)
s=(R/'039_usgs.html').read_text();a=html.unescape(re.search(r'<META NAME="abstract" CONTENT="([^"]*)',s)[1])
r=record(39,'Turbidite event history—Methods and implications for Holocene paleoseismicity of the Cascadia subduction zone','https://pubs.usgs.gov/publication/pp1661F','https://pubs.usgs.gov/pp/pp1661f/pp1661f.pdf');r.update(resolved_doi='10.3133/pp1661F',abstract=a,abstract_status='retrieved',abstract_source_url=r['paper_url'],license='USGS report is in the public domain; third-party material exceptions may apply.',full_text_status='official_publisher_link_not_downloaded',raw_source_file='coszo_retrieval_provenance/parent/raw/039_usgs.html',notes=['Full 948-word Abstract from official USGS publication record; unusually long abstract verified as complete, not article body.'],attempts=[{'url':'https://pubs.usgs.gov/publication/pp1661F','result':'Official USGS title, citation, DOI and full abstract verified.'}]);rows.append(r)
p.write_text(''.join(json.dumps(r,ensure_ascii=False)+'\n' for r in sorted(rows,key=lambda r:r['id'])))
print([(r['id'],r['abstract_status']) for r in rows])
