#!/usr/bin/env python3
import json, datetime as dt, html, re

P="/Users/quakehunter/Documents/ChatGPT/RCA Agent/tmp/coszo_abstracts/batch2/results.jsonl"
NOW=dt.datetime.now(dt.timezone.utc).isoformat()

UPDATES={
51:{"abstract":"We describe two transient slow slip events that occurred before the 2011 Tohoku-Oki earthquake. The first transient crustal deformation, which occurred over a period of a week in November 2008, was recorded simultaneously using ocean-bottom pressure gauges and an on-shore volumetric strainmeter; this deformation has been interpreted as being an M6.8 episodic slow slip event. The second had a duration exceeding 1 month and was observed in February 2011, just before the 2011 Tohoku-Oki earthquake; the moment magnitude of this event reached 7.0. The two events preceded interplate earthquakes of magnitudes M6.1 (December 2008) and M7.3 (March 9, 2011), respectively; the latter is the largest foreshock of the 2011 Tohoku-Oki earthquake. Our findings indicate that these slow slip events induced increases in shear stress, which in turn triggered the interplate earthquakes. The slow slip event source area on the fault is also located within the downdip portion of the huge-coseismic-slip area of the 2011 earthquake. This demonstrates episodic slow slip and seismic behavior occurring on the same portions of the megathrust fault, suggesting that the faults undergo slip in slow slip events can also rupture seismically.","abstract_source_url":"https://www.sciencedirect.com/science/article/pii/S0040195112004994"},
57:{"abstract":"At least 70% of the volcanism on Earth occurs along the 65,000 km network of mid-ocean ridge (MOR) spreading centers. Within these dynamic environments, the highest fluxes of heat, chemicals, and biological material from the lithosphere to the hydrosphere occur during volcanic eruptions. However, because underwater volcanoes are difficult and expensive to access, researchers are rarely, if ever, in the right place at the right time to characterize these events. Therefore, our knowledge is limited about the linkages among hydrothermal, chemical and biological processes during seafloor formation and crustal evolution. To make significant advancements in understanding the evolution of MOR environments, the United States and Canada have invested in the first plate-scale submarine cabled observatory linked through the global Internet. Spanning the Juan de Fuca tectonic plate, these two networks include >1700 km of cable and 14 subsea terminals that provide 8–10 kW power and 10 Gbs communications to hundreds of instruments on the seafloor and throughout the overlying water column — resulting in a 24/7/365 presence in the oceans. Data and imagery are available in real- to near-real time. The initial experimental sites for monitoring volcanic processes include the MOR volcanoes called Axial Seamount and the Endeavour Segment that are located on the Juan de Fuca Ridge. Axial, a hot-spot influenced seamount, is the most robust volcano along the ridge rising nearly 1400 m above the surrounding seafloor and it has erupted twice in the last 15 years. In contrast, the Endeavour Segment is characterized by more subdued topography with a well defined axial rift and it hosts one of the most intensely venting hydrothermal systems known. A non-eruptive spreading event lasting 6 years was documented at Endeavour between 1999 and 2005. Hydrothermal venting intensity, chemistry, and temperature, as well as associated biological communities at both sites were significantly perturbed by the magmatic and intrusive events. This paper presents the similarities and differences between the Axial and Endeavour volcanic systems and identifies reasons why they are ideal candidates for comparative studies. The U.S. has made a 25-year commitment for sustained observations using the cabled infrastructure. The highly expandable nature of submarine optical networking will allow for the future addition of novel experiments that utilize ever evolving advancements in computer sciences, robotics, genomics and sensor miniaturization. Comprehensive modeling of the myriad processes involved will continue to assimilate and integrate growing databases yielding a new understanding of integrated processes that create the seafloor in the global ocean basins.","abstract_source_url":"https://www.sciencedirect.com/science/article/abs/pii/S0025322714000723"},
60:{"abstract":"Goldfinger et al. (2012) interpreted a 10,000 year old sequence of deep sea turbidites at the Cascadia subduction zone (CSZ) as a record of clusters of plate-boundary great earthquakes separated by gaps of many hundreds of years. We performed statistical analyses on this inferred earthquake record to test the temporal clustering model and to calculate time-dependent recurrence intervals and probabilities. We used a Monte Carlo simulation to determine if the turbidite recurrence intervals follow an exponential distribution consistent with a Poisson (memoryless) process. The latter was rejected at a statistical significance level of 0.05. We performed a cluster analysis on 20 randomly simulated catalogs of 18 events (event T2 excluded), using ages with uncertainties from the turbidite dataset. Results indicate that 13 catalogs exhibit statistically significant clustering behavior, yielding a probability of clustering of 13/20 or 0.65. Most (70%) of the 20 catalogs contain two or three closed clusters (a sequence that contains the same or nearly the same number of events) and the current cluster T1–T5 appears consistently in all catalogs. Analysis of the 13 catalogs that manifest clustering indicates that the probability that at least one more event will occur in the current cluster is 0.82. Given that the current cluster may not be closed yet, the probabilities of an M 9 earthquake during the next 50 and 100 years were estimated to be 0.17 and 0.25, respectively. We also analyzed the sensitivity of results to including event T2, whose status as a full-length rupture event is in doubt. The inclusion of T2 did not change the probability of clustering behavior in the CSZ turbidite data, but did significantly reduce the probability that the current cluster would extend to one more event. Based on the statistical analysis, time-independent and time-dependent recurrence intervals were calculated.","abstract_source_url":"https://openalex.org/W2117738563"},
61:{"abstract":"During the decade from mid-2004 to mid-2014 18 great (Mw ≥8.0) earthquakes occurred globally (∼1.8 per year), compared to 71 from 1900 to mid-2004 (∼0.68 per year), yielding a short-term rate increase of 265%. Six events had Mw ≥8.5, larger than any prior event since the 1965 Rat Islands earthquake. The December 26, 2004 Mw 9.2 Sumatra earthquake had the longest recorded rupture length of 1300+ km and a rupture duration exceeding 450 s. The largest recorded strike-slip earthquake (Mw 8.7) occurred in the Indo–Australian plate on April 11, 2012. The largest recorded deep focus earthquake (Mw 8.3) occurred under the Sea of Okhotsk on May 24, 2013. While this overall surge of activity has not been demonstrated to be causally linked, regional spatio-temporal clustering is clearly evident for great events along the Sumatra, Kuril and Tonga subduction zones, and longer-range interactions have been established for global seismicity and seismic tremor at lower magnitudes following some of the events. This recent decade of intense great earthquake activity coincided with vastly expanded global networks of seismometers, GPS stations, tsunami gauges, and new satellite imaging capabilities such as InSAR and LandSAT interferometry and gravity measurements by GRACE and GOCE, enabling unprecedented analyses of precursory, co-seismic and post-seismic processes around the subduction zone environments where most of the events occurred. Individual events such as the March 11, 2011, Tohoku, Japan Mw 9.0 earthquake produced more ground motion and tsunami recordings than available for all great earthquakes of the last century collectively. Joint inversion and modeling of the diverse data sets exploit complementary sensitivity of the signals to different aspects of the earthquake processes. Major advances have been achieved in quantifying frictional locking and strain accumulation prior to some great events and in relating it to co-seismic slip heterogeneity. Many surprising aspects of these well-quantified great earthquakes have been manifested, associated with their rupture dimensions, tectonic location, compound faulting, triggering interactions, slow slip and foreshock migration precursors, aftershock complexity, and depth-varying seismic radiation characteristics. Regions with potential for near-future great ruptures include mature seismic gaps along the Mentawai Islands and northern Chile, as well as western North America and the Himalayan front, so more great earthquake activity can certainly be anticipated.","abstract_source_url":"https://www.sciencedirect.com/science/article/pii/S0012821X14006748"},
69:{"abstract":"Data from an amphibious seismic network in Cascadia (northwest North America) provide unique near-source observations to assess the influence of subducting topography on seismicity. Using subspace detection, we detect and locate 222 events in two separate clusters, near a subducted seamount and a possibly accreted seamount. Seismicity in both clusters is largely shallower than the plate interface and exhibits occasional swarm-like behavior. This implies that the seamount is subducting aseismically via weak coupling with the overriding plate, while earthquakes in the upper plate arise from a high degree of fracturing due to seamount interaction, and the accreted seamount induced similar fracturing before off-scraping.","abstract_source_url":"https://laro.lanl.gov/esploro/outputs/journalArticle/Newly-detected-earthquakes-in-the-Cascadia/9916369521503761"},
85:{"abstract":"One method to detect vertical crustal deformation of the seafloor, where Global Positioning System (GPS) surveys are not possible, is to monitor changes in the ambient seawater pressure, whose value is governed primarily by depth. Modern pressure sensors based on quartz strain gauge technology can detect the pressure shift associated with subsidence or uplift of the seafloor by as little as 1 cm. Such signals can be caused by tectonic or volcanic activity, or by hydrocarbon production from an offshore reservoir. However, most gauges undergo a slow drift having unpredictable sign and magnitude, which can be misinterpreted as real seafloor height change. To circumvent this problem, we have developed an instrument that calibrates the pressure gauges in place on the seafloor. In this autonomous system, a pair of quartz pressure gauges recording ambient seawater pressure are periodically connected to a piston gauge calibrator. In a 104 day test off the California coast at 664-m depth, the contribution to the uncertainty in depth variation from gauge drift was 1.3 cm based on calibrations occurring for 20 min every ten days.","abstract_source_url":"https://ieeexplore.ieee.org/document/6423803"},
86:{"abstract":"Central Cascadia between 43ºN and 46ºN has reduced interseismic uplift observed in geodetic data and coseismic subsidence seen in multiple thrust earthquakes, suggesting elevated persistent fault creep in this section of the subduction zone. We estimate subduction thrust \"decade-scale\" locking and crustal block rotations from three-component continuous Global Positioning System (GPS) time series from 1997 to 2013, as well as 80 year tide gauge and leveling-derived uplift rates. Geodetic observations indicate coastal central Oregon is rising at a slower rate than coastal Washington, southern Oregon and northern California. Modeled locking distributions suggest a wide locking transition zone that extends inland under central Oregon. Paleoseismic records of multiple great earthquakes along Cascadia indicate less subsidence in central Oregon. The Cascade thrust under central Oregon may be partially creeping for at least 6500 years (the length of the paleoseismic record), reducing interseismic uplift and resulting in reduced coseismic subsidence. Large accretions of Eocene age basalt (Siletzia terrane) between 43ºN and 46ºN may be less permeable compared to surrounding terranes, potentially increasing pore fluid pressures along the fault interface resulting in a wide zone of persistent fault creep. In a separate inversion, three-component GPS time series from 1 July 2005 to 1 January 2011 are used to estimate upper plate deformation, locking between slow-slip events (SSEs), slip from 16 SSEs and an earthquake mechanism. Cumulative SSEs and tectonic tremor are weakest between 43ºN and 46ºN where partial fault creep is increased and Siletzia terrane is thick, suggesting that surrounding rock properties may influence the mode of slip.","abstract_source_url":"https://pdxscholar.library.pdx.edu/geology_fac/83/","full_text_url":"https://pdxscholar.library.pdx.edu/geology_fac/83/"},
89:{"abstract":"The Ocean Observatories Initiative (OOI) is an integrated suite of instrumented platforms and discrete instruments that measure physical, chemical, geological, and biological properties from the seafloor to the sea surface. The OOI provides data to address large-scale scientific challenges such as coastal ocean dynamics, climate and ecosystem health, the global carbon cycle, and linkages among seafloor volcanism and life. The OOI Cyberinfrastructure currently serves over 250 terabytes of data from the arrays. These data are freely available to users worldwide, changing the way scientists and the broader community interact with the ocean, and permitting ocean research and inquiry at scales of centimeters to kilometers and seconds to decades.","abstract_source_url":"https://tos.org/oceanography/article/the-ocean-observatories-initiative","full_text_url":"https://tos.org/oceanography/assets/docs/31-1_smith2.pdf"},
}

rs=[json.loads(x) for x in open(P)]
for r in rs:
    n=int(r["id"][-3:])
    if n in UPDATES:
        r.update(UPDATES[n]);r["abstract_status"]="retrieved";r["retrieved_at"]=NOW
        r["notes"]=(r.get("notes") or "")+" Abstract manually verified against the cited scholarly source during final gap review."
        r.setdefault("attempts",[]).append({"url":r["abstract_source_url"],"result":"exact title, authors, year, and abstract verified"})
    if n==79:
        r["abstract"]=None;r["abstract_status"]="no_abstract_expected";r["abstract_source_url"]=None;r["retrieved_at"]=NOW
        r["metadata_source_url"]="https://pubs.usgs.gov/publication/70212547"
        r["notes"]="USGS publication record verifies the exact title, authors, year, and DOI and explicitly states that no abstract is available; the item is a four-page Opinion article."
        r.setdefault("attempts",[]).append({"url":"https://pubs.usgs.gov/publication/70212547","result":"verified metadata; page explicitly says no abstract available"})
    if n==71:
        r["resolved_title"]="A Vision for NSF Earth Sciences 2020-2030: Earth in Time"
        r["paper_url"]="https://www.nationalacademies.org/projects/DELS-BESR-17-06/publication/25761"
        r["source_description"]="This consensus report identifies 12 priority research questions with potential for breakthrough Earth-science insights and initiatives NSF's Division of Earth Sciences can undertake to support them."
        r["abstract_source_url"]=None;r["metadata_source_url"]="https://www.nationalacademies.org/projects/DELS-BESR-17-06/publication/25761"
        r["notes"]="Exact National Academies Press consensus-report title, year, and DOI verified on the publisher page. The publisher supplies a report description and summary rather than a discrete article abstract."
        r.setdefault("attempts",[]).append({"url":"https://nap.nationalacademies.org/resource/25761/interactive/","result":"verified publisher description; labeled source_description, not abstract"})
    if n==74:
        r["resolved_title"]="Sea Change: 2015-2025 Decadal Survey of Ocean Sciences"
        r["paper_url"]="https://www.nationalacademies.org/projects/DELS-OSB-12-03/publication/21655"
        r["source_description"]="Sea Change addresses the strategic investments necessary at NSF to ensure a robust ocean scientific enterprise over the next decade and provides guidance on research, facilities, and funding priorities."
        r["abstract_source_url"]=None;r["metadata_source_url"]="https://www.nationalacademies.org/projects/DELS-OSB-12-03/publication/21655"
        r["notes"]="Exact National Academies Press consensus-report title, year, and DOI verified on the publisher page. The publisher supplies a report description and chapter summary rather than a discrete article abstract."
        r.setdefault("attempts",[]).append({"url":"https://www.nationalacademies.org/read/21655","result":"verified publisher book record; no discrete article abstract"})
    if r.get("abstract"):
        r["abstract"]=re.sub(r"\s+"," ",html.unescape(re.sub(r"<[^>]+>"," ",r["abstract"]))).strip()
        r["abstract"]=re.sub(r"^Abstract\s+","",r["abstract"],flags=re.I)
    if r.get("resolved_title"):
        r["resolved_title"]=re.sub(r"\s+"," ",html.unescape(re.sub(r"<[^>]+>"," ",r["resolved_title"]))).strip()
    if n==59:
        r["notes"]=(r.get("notes") or "")+" Published version of record DOI 10.1029/2022JB025662 used; ESSOAr preprint DOI 10.1002/essoar.10512473.1 was identified but not retained as the resolved DOI."
    if n==75:
        r["notes"]=(r.get("notes") or "")+" Source bibliography incorrectly presents 2019 as the citation year; the conference paper and Geological Survey of Canada record are from 2004, while 2019 was the access year."
    if n==77:
        r["notes"]=(r.get("notes") or "")+" Nature Communications version of record DOI 10.1038/s41467-021-26954-w used; similarly titled 2022 EGU meeting abstract DOI 10.5194/egusphere-egu22-738 was excluded."
    if n==86:
        r["full_text_url"]=None
with open(P,"w") as f:
    for r in rs:f.write(json.dumps(r,ensure_ascii=False)+"\n")
